name: "infra preview & deploy"

on:
  push: 
    branch: 
      - main 
    paths: 
      - 10_infra/** 
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"
          