name: "infra preview & deploy"

on:
  push: 
    branch: 
      - main 
    paths: 
      - 10_infra/** 
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.2.8
  TF_PROJECT: helloworld
  TF_ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        run: |
          echo "hello"